/*
 * This source file was generated by the Gradle 'init' task
 */
package gradle.worksheet4;
import org.apache.commons.math3.stat.descriptive.DescriptiveStatistics;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        java.util.Scanner scanner = new java.util.Scanner(System.in);
        DescriptiveStatistics descriptiveStatistics = new DescriptiveStatistics();
        System.out.println("Enter numbers separated by space (e.g. 1 2 3 4):");
        String line = scanner.nextLine();
        String[] parts = line.trim().split("\\s+");
        for (String part : parts) {
            try {
                double v = Double.parseDouble(part);
                descriptiveStatistics.addValue(v);
            } catch (NumberFormatException e) {
                System.out.println("Invalid number: " + part);
            }
        }
        double mean = descriptiveStatistics.getMean();
        double median = descriptiveStatistics.getPercentile(50);
        double standardDeviation = descriptiveStatistics.getStandardDeviation();
        System.out.println("Mean: " + mean);
        System.out.println("Median: " + median);
        System.out.println("Standard Deviation: " + standardDeviation);
        System.out.println(new App().getGreeting());
    }
}
